apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Priyal-Patel0810/Priyal-Patel0810-CBD-3344-In-class-activity-2.git
    path: nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true